### ISSUE TITLE
GMW Protocol

### ISSUE THREAD

**Issue by patricia93sousa** [cryptobiu/libscapi#12]
The GMW that you have in this library is secure against active/malicious adversaries? And semi-honest/passive?
Also, the authentication http://biulibscapi.readthedocs.io/en/latest/mid_layer/mac.html#message-authentication-codes is present on the GMW too?

**Comment by moriyaw** [comment]
The GMW is secure against semi honest adversaries. 
There is no mac is GMW...

**Comment by patricia93sousa** [comment]
So which protocol has Mac and against malicious ?

Em 02/04/2017 6:40 da manhã, "moriyaw" <notifications@github.com> escreveu:

**Comment by patricia93sousa** [comment]
YaoSingleExecution, for example, it has?

**Comment by moriyaw** [comment]
We didn't implement such protocol.
You are welcome to search for such protocol in cryptographic papers and implement it. 

Feel free to make a pull request after you are done.

Good Luck :)

**Comment by patricia93sousa** [comment]
But you have Yao against malicious... You don't make any type of authentication ?

**Comment by moriyaw** [comment]
See the paper at https://eprint.iacr.org/2015/987
