### ISSUE TITLE
Double-free issues in generateSendableData() methods

### ISSUE THREAD

**Issue by schoppmp** [cryptobiu/libscapi#17]
Many of the classes defined in `include/CryptoInfra/PlainText.hpp` that derive from `NetworkSerialized` override the `generateSendableData()` in the following way:
```[C++]
shared_ptr<AsymmetricCiphertextSendableData> generateSendableData() {
	return shared_ptr<AsymmetricCiphertextSendableData>(this);
}
```
See class [BigIntegerCiphertext for an example](https://github.com/cryptobiu/libscapi/blob/0068cdb4169dcd60cc967e2e5c93143083c1fa7f/include/CryptoInfra/PlainText.hpp#L228).

The problem here is that this method wraps a pointer to an existing object in a `shared_ptr`. Thus, when the pointer returned by `generateSendableData()` goes out of scope, it frees the object pointed to by `this`, even if it is still accessible. Then, when the original object goes out of scope, it gets freed again, resulting in a double-free error.

A minimal example:
```[C++]
#include "CryptoInfra/PlainText.hpp"
#include <iostream>

int main() {
    auto a = BigIntegerCiphertext(3);
    std::cout << a.generateSendableData() << "\n";
    std::cout << a.toString() << "\n";
}
```
A possible fix would be to pass an empty destructor to the `shared_ptr` constructor, so that it doesn't delete anything when going out of scope:
```[C++]
shared_ptr<AsymmetricCiphertextSendableData> generateSendableData() {
	return shared_ptr<AsymmetricCiphertextSendableData>(this, [](void*){});
}
```
That way, implementations of `generateSendableData()` that actually allocate memory can still manage it using a `shared_ptr`, but those that don't (such as `BigIntegerCiphertext`) will not cause double-free errors.
However, I'm not sure if some other part of your code somehow relies on the object being destroyed after calling `generateSendableData()`. If that's not the case, I can open a pull request that fixes the issue as described above.

**Comment by moriyaw** [comment]
Fixed. 
Thank you for your comment!
