### ISSUE TITLE
File to be removed?

### ISSUE THREAD

**Issue by fabrice102** [cryptobiu/libscapi#32]
I think that the following file should be removed from the repository:

https://github.com/cryptobiu/libscapi/blob/master/samples/bilinar/a.txt

Furthermore, the name of the parent folder looks like a typo: `bilinar` instead of `bilinear`.

**Comment by liorbiu** [comment]
Of course, I fixed the typo.
Thank you

**Comment by fabrice102** [comment]
Thanks.

I think you did not remove the original folder (`bilinar`).

**Comment by liorbiu** [comment]
I removed it.
Thanks.
