### ISSUE TITLE
Building SCAPI without root

### ISSUE THREAD

**Issue by lenerd** [cryptobiu/libscapi#34]
Hello,

during the build of libscapi by calling `make` the following error occurs.

```
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: /usr/local/include/relic.  Maybe need
  administrative privileges.


make[1]: *** [Makefile:107: install] Error 1
make[1]: Leaving directory '/path/to/libscapi/build/EMP/relic'
make: *** [makefile:71: prepare-emp] Error 2
```

Of course, running `sudo make` would allow to create the directory under `/usr/local`. But, for once, I hesitate to compile with root permissions and I would like to avoid installing it globally on my system. Then, on other systems I might not have sufficient permissions.

The problem to solve seems to be to put the `relic` header somewhere, where they can be found by the other libraries. This should be possible without installing this stuff globally.

I have currently a limited overview of the build process and would like to ask if anyone has worked on this problem already?

**Comment by fabrice102** [comment]
Please see #10.

**Comment by fabrice102** [comment]
You can replace `sudo ldconfig ~/boost_1_60_0/stage/lib/ ~/libscapi/install/lib/` by adding `export LD_LIBRARY_PATH=$HOME/boost_1_60_0/stage/lib:$HOME/libscapi/install/lib:$LD_LIBRARY_PATH` in `~/.bashrc`, `~/.zshrc`, or a similar file (and by opening a new shell).

**Comment by lenerd** [comment]
Thank you,

unfortunately it did not work out of the box for me.
The relic headers and library were not found. With [these modifications](https://github.com/fabrice102/libscapi/compare/make-no-sudo...lenerd:make-no-sudo) I was able to build the EMP libraries on my system (I did remove `-I${HOME}/boost_1_60_0 ` from the Makefile).

However, the OpenSSL version stopped me from completing the build. I will continue later with the other SCAPI branch as explained [here](https://github.com/cryptobiu/libscapi/issues/3#issuecomment-296654090).

**Comment by fabrice102** [comment]
Yes indeed, you need to do that. I actually did pull requests to update `emp`: #20, #21, #29. I forgot it was necessary.

**Comment by lenerd** [comment]
So, with [a few adjustments for my Arch Linux system](/lenerd/libscapi/tree/build-archlinux) I have got a compiling source tree.

@fabrice102 Thanks for your help and your PRs.

**Comment by abarak-biu** [comment]
This has been resolved. You can build the latest master version without root
