### ISSUE TITLE
Boost status in the build is a tad unclear

### ISSUE THREAD

**Issue by srpgilles** [cryptobiu/libscapi#42]
In the [installation guide for Linux](http://biulibscapi.readthedocs.io/en/latest/install.html#installing-libscapi-linux), you mention Boost 1.60 must be installed.

However, during the build of libscapi an embedded Boost 1.64 is installed...

I therefore tried not to install the external Boost library (i.e. the 1.60 version); in this case all compiles well... until I try the sample compilation, which complains about the lack of Boost serialization. I checked, and indeed only a subset of Boost libraries is installed, with serialization omitted:

<img width="320" alt="screen shot 2017-12-26 at 09 21 12" src="https://user-images.githubusercontent.com/1656139/34351619-2efb386a-ea1e-11e7-9477-beb7f471f80d.png">

Wouldn't it be cleaner to omit the Boost 1.60 step and add serialization (and potentially other required Boost modules) in the libscapi build?

**Comment by liorbiu** [comment]
Hi @srpgilles 
Thank you for your comment, I will update the libscapi documentation.
Your PR #43 will solve the problem.
