### ISSUE TITLE
Boost error while compiling

### ISSUE THREAD

**Issue by MaryLouPap** [cryptobiu/libscapi#46]
I tried to compile the code on the Quickstart page and came across this particular error:
```
In file included from libscapi/include/primitives/Dlog.hpp:31:0,
                 from libscapi/include/primitives/DlogOpenSSL.hpp:34,
                 from scapistart.cpp:1:
libscapi/include/primitives/../infra/Common.hpp:33:28: fatal error: boost/random.hpp: No such file or directory
 #include <boost/random.hpp>
                            ^
compilation terminated.
```
Apparently it's something in the library itself.

We want to use libscapi for our undergraduate thesis, which will be part of a project concerning SMPC undertaken by ATHENA Research & Innovation Center in Athens. It is very important for us to make this work, so any help would be greatly appreciated.

**Comment by abarak-biu** [comment]
Hi.  Some quick questions:

1. You need to git clone libscapi under your home directory  ( "~/"),
"/home/ab" on mine. Install does not work from another directory (we will
update instructions to clarify)

2. Which version of gcc and linux are you using?

I am running a clean install for sanity, to see if the installation is
broken for another reason

Assi

**Comment by MaryLouPap** [comment]
1. Libscapi is indeed in my home directory.
2. The versions are:
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
Ubuntu: 16.04.4 LTS (Xenial Xerus)

Tests and samples seem to work properly. It is when I run the instructions on Quickstart and reach the first compilation instruction that this happens.

P.S. I believe there is some minor inconsistency there as well, as the library included in the instruction is scapi.a and not libscapi.a

**Comment by abarak-biu** [comment]
Ok , I understand the problem now

  - The instructions in
http://biulibscapi.readthedocs.io/en/latest/quickstart.html are obsolete.

  - Installation instructions are here:
https://github.com/cryptobiu/libscapi/blob/master/build_scripts/INSTALL.MD
       - Note that we do not need a boost installation.
       - However as things are working for you, I believe you installed
correctly.

- the line to compile is not valid:

$ g++ example.cpp -I/home/moriya -I/home/moriya/boost_1_60_0
-std=c++11 scapi.a -lboost_system
-L/home/moriya/boost_1_60_0/stage/lib -lssl -lcrypto -lgmp

I will run a short test and send you the line shortly.

Assi

**Comment by stathisKara** [comment]
Hey,
I am working together with MaryLouPap above. Any updates on the compilation command ?
Any guidelines for compiling since the project is still developing and the compilation command might change again ?
Thanks

Stathis

**Comment by liorbiu** [comment]
Hello,

I created a new file called libscapiTests.cpp at my home directory. I managed to compile it using this command:
`g++ -I. -Ilibscapi/install/include testLibscapi.cpp libscapi/libscapi.a -Llibscapi/install/lib -lgmp libscapi/install/lib/libssl.a libscapi/install/lib/libcrypto.a -ldl -lz`

**Comment by MaryLouPap** [comment]
Hi,

I just had a chance to run this command and I got a ton of compilation errors. Probably an include is incorrect or a library's missing or misplaced. I have attached the errors. Any pointers?

Mary
[log.txt](https://github.com/cryptobiu/libscapi/files/2032016/log.txt)

**Comment by liorbiu** [comment]
Please add your makefile/compilation line.

**Comment by abarak-biu** [comment]
You might be missing the -std=c++14 switch

g++ *-std=c++14* -I. -Ilibscapi/install/include testLibscapi.cpp
libscapi/libscapi.a -Llibscapi/install/lib -lgmp
libscapi/install/lib/libssl.a libscapi/install/lib/libcrypto.a -ldl -lz

**Comment by MaryLouPap** [comment]
Yes, that was it. Thank you.
