### ISSUE TITLE
variable name

### ISSUE THREAD

**Issue by sefi-roee** [cryptobiu/libscapi#47]
https://github.com/cryptobiu/libscapi/blob/7a469718bfc8ceaed26fe94eedfbbfd95b30cdd7/include/primitives/Mersenne.hpp#L268

Maybe should be changed to low62to64 or something.

**Comment by liorbiu** [comment]
Changed at [https://github.com/cryptobiu/libscapi/commit/660a94ecb42fdeff15ed77d216ead4565dd9d124](url)

**Comment by liorbiu** [comment]
Changed at [](https://github.com/cryptobiu/libscapi/commit/660a94ecb42fdeff15ed77d216ead4565dd9d124)
