### ISSUE TITLE
Error executing an example

### ISSUE THREAD

**Issue by patricia93sousa** [cryptobiu/libscapi#5]
I'm trying to make: 

> 
./libscapi_example commitment 1 Comm/CommConfig.txt 

But I get the error: 

> terminate called after throwing an instance of 'char const*'
> Aborted (core dumped)

**Comment by liorbiu** [comment]
If you like to run the commitment example, you will need to open two different terminals.

In the first terminal run `./libscapi_example commitment 1 Commitment/CommitmentConfig.txt`

In the second terminal run `./libscapi_example commitment 2 Commitment/CommitmentConfig.txt`

The Comm folder is using for communication samples.

In order to see use examples follow this [link](https://scapi.readthedocs.io/en/latest/cpp_beta.html#samples)

**Comment by patricia93sousa** [comment]
Thanks! It solve the problem. I followed this link but the examples are wrong.

**Comment by patricia93sousa** [comment]
Only another question, how can I test the example "test.cpp" in "bilinar" folder?

**Comment by patricia93sousa** [comment]
>  ./libscapi_example comm 1 Comm/CommConfig.txt 

Why this example doesn't run?
> 
> To run an example:
> ./libscapi_examples <example_name> [args...]
> 
> example_name can one of the following: 
> 	* dlog
> 	* sha1
> 	* maliciousOT <party_number (1|2)>
> 	* semiHonestOT <party_number (1|2)>
> 	* comm		  <party_number (1|2)> <config_file_path>
> 	* yao		  <party_number (1|2)> <config_file_path>
> 	* sigma		  <party_number (1|2)> <config_file_path>
> 	* commitment  <party_number (1|2)> <config_file_path>
> 	* ot  <party_number (1|2)> <config_file_path>
> 	* OTExtensionBristol <party_number (0|1)> (linux only) 
> 	* ospsi input_file_1 input_file_2
>

**Comment by patricia93sousa** [comment]
I want the "equality" of the Comm folder. How can I make to compile de Comm folder and execute?

**Comment by CryptoBIUUser** [comment]
Thank you for your comment. It was a bug in executing the communication folder.
I updated the samples folder. Just do `git pull` and build the samples again.

All the examples beside dlog, sha1 and ospsi (out sourced private set intersection) request two terminals (terminal for each party).

**Comment by liorbiu** [comment]
Thank you for your comment. It was a bug in executing the communication folder.
I updated the samples folder. Just do `git pull` and build the samples again.

All the examples beside dlog, sha1 request two terminals.

**Comment by patricia93sousa** [comment]
./libscapi_example comm 1 Comm/CommConfig.txt

> ./libscapi_example: error while loading shared libraries: libOTExtension.so: cannot open shared object file: No such file or directory

You know anything about this error now?

Thanks

**Comment by patricia93sousa** [comment]
Thank you so much! Nice work
