### ISSUE TITLE
OpenSSL & MacOS Build Process (on High Sierra)

### ISSUE THREAD

**Issue by dahadaller** [cryptobiu/libscapi#53]
I have also replicated this same problem in a colleague's (Bon, who is also on this thread) computer on High Sierra 10.13, too. My computer has Mojave. The compiler used on High Sierra computer was clang.

```
Bons-MacBook-Pro:~ bon$ ls -l $(which cc)
lrwxr-xr-x  1 root  wheel  5 Oct 26 21:22 /usr/bin/cc -> clang

Bons-MacBook-Pro:libscapi bon$ ls -l $(which g++)
-rwxr-xr-x  1 root  wheel  18288 Sep 21 00:17 /usr/bin/g++

Bons-MacBook-Pro:libscapi bon$ g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 
```

_Originally posted by @dahadaller in https://github.com/cryptobiu/libscapi/issue_comments#issuecomment-437043808_

**Comment by liorko87** [comment]
Hello @dahadaller,

I succeeded to compile on brand new mac with High Sierra using g++
I created a new branch that called `mac`, please use this branch.
