### ISSUE TITLE
Compiling error on Mac Mojave

### ISSUE THREAD

**Issue by antidb** [cryptobiu/libscapi#54]
I'm followed the installation instruction, and make process seems successful, but failed on illegal copy.

 [90%] Building CXX object libOTe_Tests/CMakeFiles/libOTe_Tests.dir/UnitTests.cpp.o
[ 92%] Linking CXX static library ../lib/liblibOTe_Tests.a
[ 92%] Built target libOTe_Tests
Scanning dependencies of target frontend_libOTe
[ 93%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/CLP.cpp.o
[ 95%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/main.cpp.o
[ 96%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/signalHandle.cpp.o
[ 98%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/util.cpp.o
[100%] Linking CXX executable ../bin/frontend_libOTe
[100%] Built target frontend_libOTe
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
make: *** [compile-libote] Error 1

But the libscapi.a doesn't generated, so the tests make failed:

g++ -std=c++11 -maes -mavx -I/usr/include/openssl -I../install/include -o tests.exe tests.cpp interactiveMidProtocolsTests.cpp ../libscapi.a -ldl -lpthread -L../install/lib -lssl -lboost_system -lntl -lgmp -lcrypto
clang: error: no such file or directory: '../libscapi.a'
make: *** [tests.exe] Error 1

The example make also failed:

In file included from Yao/App1.cpp:29:
In file included from Yao/YaoExample.hpp:36:
Yao/../../include/interactive_mid_protocols/OTExtensionBristol.hpp:31:10: fatal error: 'OTExtensionBristol/OT/OTExtensionWithMatrix.h' file not found
#include <OTExtensionBristol/OT/OTExtensionWithMatrix.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [App1.o] Error 1

**Comment by ZhijieWang** [comment]
due to incompatibility between OSX coretuils and Linux coreutils. You could solve this by using homebrew and install coretuils. Or change the cp flag.

**Comment by Yiping106283** [comment]
This is because `cp --parent` does not work. Changing it to `rsync -R` works for me.

**Comment by lemonviv** [comment]
I've got the same error. The make process is successful, but the cp -r command does not work. My OS is Ubuntu 16.04, g++ version is 7.4.0, do you have any suggestion to solve this problem? Thanks.

How to change the cp flag or to "rsync -R"? @ZhijieWang  @Yiping106283 

The error in makefile is: 

# Support only in c++14
compile-libote:
	@echo "Compiling libOTe library..."
	@cp -r lib/libOTe $(builddir)/libOTe 

make[3]: Leaving directory '/home/wuyuncheng/Documents/projects/libscapi/build/libOTe'
make[3]: Entering directory '/home/wuyuncheng/Documents/projects/libscapi/build/libOTe'
[ 93%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/CLP.cpp.o
[ 95%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/main.cpp.o
[ 96%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/signalHandle.cpp.o
[ 98%] Building CXX object frontend/CMakeFiles/frontend_libOTe.dir/util.cpp.o
[100%] Linking CXX executable ../bin/frontend_libOTe
make[3]: Leaving directory '/home/wuyuncheng/Documents/projects/libscapi/build/libOTe'
[100%] Built target frontend_libOTe
make[2]: Leaving directory '/home/wuyuncheng/Documents/projects/libscapi/build/libOTe'
make[1]: Leaving directory '/home/wuyuncheng/Documents/projects/libscapi/build/libOTe'
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
cp: with --parents, the destination must be a directory
Try 'cp --help' for more information.
makefile:164: recipe for target 'compile-libote' failed
make: *** [compile-libote] Error 123

**Comment by liorko87** [comment]
The latest version of `libscapi` compiles with no errors on OSX
