### ISSUE TITLE
Error making Scapi (libOTe)

### ISSUE THREAD

**Issue by Ruth1993** [cryptobiu/libscapi#55]
Hi people,

When I make Scapi, I get the following error in building libOTe on Ubuntu 18.04:

[ 40%] Building CXX object cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/Tutorials/Network.cpp.o
[ 41%] Building CXX object cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/main.cpp.o
[ 43%] Building CXX object cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/signalHandle.cpp.o
[ 45%] Linking CXX executable ../../bin/frontend_cryptoTools
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/build.make:150: recipe for target 'bin/frontend_cryptoTools' failed
make[3]: *** [bin/frontend_cryptoTools] Error 1
make[3]: Leaving directory '/home/osboxes/libscapi/build/libOTe'
CMakeFiles/Makefile2:253: recipe for target 'cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/all' failed
make[2]: *** [cryptoTools/frontend_cryptoTools/CMakeFiles/frontend_cryptoTools.dir/all] Error 2
make[2]: Leaving directory '/home/osboxes/libscapi/build/libOTe'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/osboxes/libscapi/build/libOTe'
makefile:246: recipe for target 'compile-libote' failed
make: *** [compile-libote] Error 2

Could anyone help me with this error? Thanks in advance!

**Comment by liorko87** [comment]
Hello @Ruth1993,

Please install this library: `sudo apt install zlib1g-dev`.
Afterwards run: `make clean && make`.
I will add it to our install instructions.

Lior

**Comment by Ruth1993** [comment]
Thanks a lot, it works!
