### ISSUE TITLE
Cannot make libscapi

### ISSUE THREAD

**Issue by bottavin** [cryptobiu/libscapi#56]
I followed the instruction listed in the page https://biulibscapi.readthedocs.io/en/latest/install.html to install libscapi on linux. When I launched the make command I received the following message: 
No rule to make libs

**Comment by bottavin** [comment]
It seems that the error is generated by the fact that the architecture of my computer is 32 bit, but I didn't find this limitation of the documentation

**Comment by liorko87** [comment]
@bottavin libscapi does not support 32 bit.
I will add this to the documentation.
