### ISSUE TITLE
Can't build examples

### ISSUE THREAD

**Issue by gdalc** [cryptobiu/libscapi#59]
Hi, the library is correctly installed since it passes all the tests.
Unfortunately I can't build examples in libscapi/examples as in https://biulibscapi.readthedocs.io/en/latest/install.html#samples.

When I launch make, the output is the following:

> g++  --std=c++14 -I../../boost_1_64_0 -I../install/include -I../lib/OTExtensionBristol -I../install/include/libOTe -I../install/include/libOTe/cryptoTools -O3 -Wall -Wno-unused-function -Wno-unused-variable -Wno-expansion-to-defined -Wno-ignored-attributes -no-pie examples_main.cpp -o libscapi_example simple_dlog.o simple_sha1.o simple_gmac.o CommitmentExample.o OTExample.o SigmaProtocolExample.o comm_example.o App1.o YaoParties.o OTExtensionBristolExample.o ../libscapi.a ../install/lib/libOTExtensionBristol.a ../install/lib/libOTe.a ../install/lib/libcryptoTools.a ../install/lib/libmiracl.a ../install/lib/libsimpleot.a -L../install/lib -L../../boost_1_64_0/stage/lib ../install/lib/libcrypto.a -ldl -lboost_log -lboost_system -lboost_thread -lboost_serialization -lboost_filesystem -lpthread ../install/lib/libssl.a -lgmp -lrt
> g++: error: ../install/lib/libcrypto.a: No such file or directory
> g++: error: ../install/lib/libssl.a: No such file or directory
> makefile:11: recipe for target 'libscapi_example' failed
> make: *** [libscapi_example] Error 1

Thanks, Giuseppe.

**Comment by liorko87** [comment]
Hi @gdalc,

Please try again now. I applied the changes from the dev branch to the master.
Pull the latest version of libscapi using `git pull` and try again

Lior
