### ISSUE TITLE
Boost error when running communication example from tutorial

### ISSUE THREAD

**Issue by Ruth1993** [cryptobiu/libscapi#60]
Hello,

I'm trying to set up communication channels for two parties using the tutorial and code provided by https://biulibscapi.readthedocs.io/en/latest/quickstart.html (the part on Establishing Secure Communication). The problem is that it's not clear to me how I should compile, because when I compile, it works, but then when I try to run it, it gives me the following error:

`error while loading shared libraries libboost_system.so:1.64.0: cannot open shared object file`

I'm using the following line to compile:

`g++ communication.cpp -I/home/name -I/home/name/boost_1_64_0 -std=c++14 ../libscapi/libscapi.a -ldl -lboost_log -lboost_system -lboost_thread -lboost_serialization -lboost_filesystem -L/home/name/boost_1_64_0/stage/lib -lssl -lcrypto -lgmp -lpthread`

The example files in the folder libscapi/examples are working though, so I've already tried looking at the makefile to see what is in there, but it would be very helpful for beginning users like me to show how to compile. :) Thanks in advance!

Kind regards, Ruth

**Comment by liorko87** [comment]
Hello,

Please make sure that all the dependencies are updated and [installed](https://github.com/cryptobiu/libscapi/blob/master/build_scripts/INSTALL.md). I added the `libboost-all-dev` as a dependency.

After you installed all the dependencies, try to compile with this command:

`g++ communication.cpp -I/home/name -std=c++14 ../libscapi/libscapi.a -ldl -lboost_log -lboost_system -lboost_thread -lboost_serialization -lboost_filesystem  -lssl -lcrypto -lgmp -lpthread`

**Comment by Ruth1993** [comment]
Thanks a lot, it works!
