### ISSUE TITLE
Error when running commitment scheme example copied to own system

### ISSUE THREAD

**Issue by Ruth1993** [cryptobiu/libscapi#61]
Hello :),

When I run the commitment scheme example from the example folder by opening two windows and running ./libscapi_example commitment 1 Commitment/CommitmentConfig.txt in one window and ./libscapi_example commitment 2 Commitment/CommitmentConfig.txt in the other, it works perfectly. However, I copied the files examples_main.cpp, examples_main.hpp, makefile and the folder Commitment to my own system (and changed the folder names in the #include lines accordingly of course) and then I tried executing the same things again. When I first run ./libscapi_example commitment 1 Commitment/CommitmentConfig.txt in one window I get no errors, but as soon as I enter ./libscapi_example commitment 2 Commitment/CommitmentConfig.txt in the other window, I get the following error:

`terminate after throwing instance of char const*`

Does anyone know the problem? I mean, I basically just copied the code from the example folder, so I guess the problem is not with the code, but somewhere in my system.

Btw, I'm using Ubuntu 14.04 with OpenSSL 1.0.2g.

Thanks in advance!

Kind regards, Ruth

**Comment by liorko87** [comment]
Hi @Ruth1993 ,

In the [Dlog](https://github.com/cryptobiu/libscapi/blob/master/include/primitives/Dlog.hpp#L813)  implementation there is a reference to a file that names: `NISTEC.txt`. In order to avoid the exception, please copy it to the specified location or change the the `Dlog.hpp` definition

Lior

**Comment by Ruth1993** [comment]
Thanks, it works!
