### ISSUE TITLE
Cannot be installed on windows (missing libraries)

### ISSUE THREAD

**Issue by Zeinab-Rahmani** [cryptobiu/libscapi#64]
Hello, I am trying to install this library on windows and I am following the exact structures mentioned in https://biulibscapi.readthedocs.io/en/latest/install.html#installing-libscapi-windows. 
1. I installed, git, Visual Studio 2019, open ssl, and boost binaries for windows.
2. I cloned libscapi from GitHub.

And here comes my problem: in the next step it says:
Build Miracl for windows 64:
Open solution MiraclWin64.sln at: C:\code\libscapi\lib\MiraclCompilation
Build the solution once for debug and once for release.

But when I go to C:\code\libscapi\lib there is no such a file (MiraclCompilation) and also there is no any MiraclWin64.sln.  I have the same problem for other libraries (NTL-WIN64.sln, OTExtension.sln, etc).
I would really appreciate if you could help me with this problem as soon as possible.

**Comment by liorko87** [comment]
Hello,

Libscapi does not support on Windows.
I'm sorry for the outdated docs.

**Comment by Zeinab-Rahmani** [comment]
I will try it on ubuntu. Thank you so much.
