### ISSUE TITLE
get error when following the Tutorials on https://biulibscapi.readthedocs.io/en/latest/quickstart.html

### ISSUE THREAD

**Issue by lingering** [cryptobiu/libscapi#66]
**Describe the bug**
when  following the step and compile the first example successfully, I get an error 
terminate called after throwing an instance of 'char const.

after a few testing, I found that the error was causedby inti an new class OpenSSLDlogECF2m on the first line.

and after audit the source code, I notice that class OpenSSLDlogECF2m  need three parameters,
in include/primitives/DlogOpenSSL.hpp line 220:
void init(string fileName, string curveName, const shared_ptr<PrgFromOpenSSLAES> & random) override;

But after passing three parameters to this class I still get the same error.what can I do?

**Machine details (please complete the following information):**
Directly, I'm on ubuntn 18.04 using Docker image of libscapi

**Comment by liorko87** [comment]
What is the error?

**Comment by lingering** [comment]
> 
> 
> What is the error?

terminate called after throwing an instance of 'char const*'
Aborted (core dumped)

**Comment by liorko87** [comment]
Please specify output of this `ls` command:
`ls <libscapi_path>include/configFiles`

**Comment by lingering** [comment]
> 
> 
> Please specify output of this `ls` command:
> `ls <libscapi_path>include/configFiles`
after exec ls command i got NISTEC.txt file in that folder

and the context of NISTEC.txt is :
# NIST recomended elliptic curves

[P-192]
P-192 = 6277101735386680763835789423207666416083908700390324961279
a = -3
b = 64210519 e59c80e7 0fa7e9ab 72243049 feb8deec c146b9b1
r = 6277101735386680763835789423176059013767194773182842284081
x = 188da80e b03090f6 7cbf20eb 43a18800 f4ff0afd 82ff1012
y = 07192b95 ffc8da78 631011ed 6b24cdd5 73f977a1 1e794811
h = 1

[P-224]
P-224 = 26959946667150639794667015087019630673557916260026308143510066298881
a = -3
b = b4050a85 0c04b3ab f5413256 5044b0b7 d7bfd8ba 270b3943 2355ffb4
r = 26959946667150639794667015087019625940457807714424391721682722368061
x = b70e0cbd 6bb4bf7f 321390b9 4a03c1d3 56c21122 343280d6 115c1d21
y = bd376388 b5f723fb 4c22dfe6 cd4375a0 5a074764 44d58199 85007e34
h = 1

[P-256]
P-256 = 115792089210356248762697446949407573530086143415290314195533631308867097853951
a = -3
b = 5ac635d8 aa3a93e7 b3ebbd55 769886bc 651d06b0 cc53b0f6 3bce3c3e 27d2604b
r = 115792089210356248762697446949407573529996955224135760342422259061068512044369
x = 6b17d1f2 e12c4247 f8bce6e5 63a440f2 77037d81 2deb33a0 f4a13945 d898c296
y = 4fe342e2 fe1a7f9b 8ee7eb4a 7c0f9e16 2bce3357 6b315ece cbb64068 37bf51f5
h = 1

[P-384]
P-384 = 39402006196394479212279040100143613805079739270465446667948293404245721771496870329047266088258938001861606973112319
a = -3
b = b3312fa7 e23ee7e4 988e056b e3f82d19 181d9c6e fe814112 0314088f 5013875a c656398d 8a2ed19d 2a85c8ed d3ec2aef
r = 39402006196394479212279040100143613805079739270465446667946905279627659399113263569398956308152294913554433653942643
x = aa87ca22 be8b0537 8eb1c71e f320ad74 6e1d3b62 8ba79b98 59f741e0 82542a38 5502f25d bf55296c 3a545e38 72760ab7
y = 3617de4a 96262c6f 5d9e98bf 9292dc29 f8f41dbd 289a147c e9da3113 b5f0b8c0 0a60b1ce 1d7e819d 7a431d7c 90ea0e5f
h = 1

[P-521]
P-521 = 6864797660130609714981900799081393217269435300143305409394463459185543183397656052122559640661454554977296311391480858037121987999716643812574028291115057151
a = -3
b = 00000051 953eb961 8e1c9a1f 929a21a0 b68540ee a2da725b 99b315f3 b8b48991 8ef109e1 56193951 ec7e937b 1652c0bd 3bb1bf07 3573df88 3d2c34f1 ef451fd4 6b503f00
r = 6864797660130609714981900799081393217269435300143305409394463459185543183397655394245057746333217197532963996371363321113864768612440380340372808892707005449
x = 000000c6 858e06b7 0404e9cd 9e3ecb66 2395b442 9c648139 053fb521 f828af60 6b4d3dba a14b5e77 efe75928 fe1dc127 a2ffa8de 3348b3c1 856a429b f97e7e31 c2e5bd66
y = 00000118 39296a78 9a3bc004 5c8a5fb4 2c7d1bd9 98f54449 579b4468 17afbd17 273e662c 97ee7299 5ef42640 c550b901 3fad0761 353c7086 a272c240 88be9476 9fd16650
h = 1

[B-163]
B-163 = 163
k = 3
k2 = 6
k3 = 7
a = 1
b = 00000002 0a601907 b8c953ca 1481eb10 512f7874 4a3205fd
r = 5846006549323611672814742442876390689256843201587
x = 00000003 f0eba162 86a2d57e a0991168 d4994637 e8343e36
y = 00000000 d51fbc6c 71a0094f a2cdd545 b11c5c0c 797324f1
h = 1

[K-163]
K-163 = 163
k = 3
k2 = 6
k3 = 7
a = 1
b = 01
r = 5846006549323611672814741753598448348329118574063
x = 00000002 fe13c053 7bbc11ac aa07d793 de4e6d5e 5c94eee8
y = 00000002 89070fb0 5d38ff58 321f2e80 0536d538 ccdaa3d9
h = 2

[B-233]
B-233 = 233
k = 74
a = 1
b = 00000066 647ede6c 332c7f8c 0923bb58 213b333b 20e9ce42 81fe115f 7d8f90ad
r = 6901746346790563787434755862277025555839812737345013555379383634485463
x = 000000fa c9dfcbac 8313bb21 39f1bb75 5fef65bc 391f8b36 f8f8eb73 71fd558b
y = 00000100 6a08a419 03350678 e58528be bf8a0bef f867a7ca 36716f7e 01f81052
h = 1

[K-233]
K-233 = 233
k = 74
a = 0
b = 01
r = 3450873173395281893717377931138512760570940988862252126328087024741343
x = 00000172 32ba853a 7e731af1 29f22ff4 149563a4 19c26bf5 0a4c9d6e efad6126
y = 000001db 537dece8 19b7f70f 555a67c4 27a8cd9b f18aeb9b 56e0c110 56fae6a3
h = 4

[B-283]
B-283 = 283
k = 5
k2 = 7
k3 = 12
a = 1
b = 027b680a c8b8596d a5a4af8a 19a0303f ca97fd76 45309fa2 a581485a f6263e31 3b79a2f5
r = 7770675568902916283677847627294075626569625924376904889109196526770044277787378692871
x = 05f93925 8db7dd90 e1934f8c 70b0dfec 2eed25b8 557eac9c 80e2e198 f8cdbecd 86b12053
y = 03676854 fe24141c b98fe6d4 b20d02b4 516ff702 350eddb0 826779c8 13f0df45 be8112f4
h = 1

[K-283]
K-283 = 283
k = 5
k2 = 7
k3 = 12
a = 0
b = 01
r = 3885337784451458141838923813647037813284811733793061324295874997529815829704422603873
x = 0503213f 78ca4488 3f1a3b81 62f188e5 53cd265f 23c1567a 16876913 b0c2ac24 58492836
y = 01ccda38 0f1c9e31 8d90f95d 07e5426f e87e45c0 e8184698 e4596236 4e341161 77dd2259
h = 4

[B-409]
B-409 = 409
k = 87
a = 1
b = 0021a5c2 c8ee9feb 5c4b9a75 3b7b476b 7fd6422e f1f3dd67 4761fa99 d6ac27c8 a9a197b2 72822f6c d57a55aa 4f50ae31 7b13545f
r = 661055968790248598951915308032771039828404682964281219284648798304157774827374805208143723762179110965979867288366567526771
x = 015d4860 d088ddb3 496b0c60 64756260 441cde4a f1771d4d b01ffe5b 34e59703 dc255a86 8a118051 5603aeab 60794e54 bb7996a7
y = 0061b1cf ab6be5f3 2bbfa783 24ed106a 7636b9c5 a7bd198d 0158aa4f 5488d08f 38514f1f df4b4f40 d2181b36 81c364ba 0273c706
h = 1

[K-409]
K-409 = 409
k = 87
a = 0
b = 01
r = 330527984395124299475957654016385519914202341482140609642324395022880711289249191050673258457777458014096366590617731358671
x = 0060f05f 658f49c1 ad3ab189 0f718421 0efd0987 e307c84c 27accfb8 f9f67cc2 c460189e b5aaaa62 ee222eb1 b35540cf e9023746
y = 01e36905 0b7c4e42 acba1dac bf04299c 3460782f 918ea427 e6325165 e9ea10e3 da5f6c42 e9c55215 aa9ca27a 5863ec48 d8e0286b
h = 4

[B-571]
B-571 = 571
k = 2
k2 = 5
k3 = 10
a = 1
b = 02f40e7e 2221f295 de297117 b7f3d62f 5c6a97ff cb8ceff1 cd6ba8ce 4a9a18ad 84ffabbd 8efa5933 2be7ad67 56a66e29 4afd185a 78ff12aa 520e4de7 39baca0c 7ffeff7f 2955727a
r = 3864537523017258344695351890931987344298927329706434998657235251451519142289560424536143999389415773083133881121926944486246872462816813070234528288303332411393191105285703
x = 0303001d 34b85629 6c16c0d4 0d3cd775 0a93d1d2 955fa80a a5f40fc8 db7b2abd bde53950 f4c0d293 cdd711a3 5b67fb14 99ae6003 8614f139 4abfa3b4 c850d927 e1e7769c 8eec2d19
y = 037bf273 42da639b 6dccfffe b73d69d7 8c6c27a6 009cbbca 1980f853 3921e8a6 84423e43 bab08a57 6291af8f 461bb2a8 b3531d2f 0485c19b 16e2f151 6e23dd3c 1a4827af 1b8ac15b
h = 1

[K-571]
K-571 = 571
k = 2
k2 = 5
k3 = 10
a = 0
b = 01
r = 1932268761508629172347675945465993672149463664853217499328617625725759571144780212268133978522706711834706712800825351461273674974066617311929682421617092503555733685276673
x = 026eb7a8 59923fbc 82189631 f8103fe4 ac9ca297 0012d5d4 60248048 01841ca4 43709584 93b205e6 47da304d b4ceb08c bbd1ba39 494776fb 988b4717 4dca88c7 e2945283 a01c8972
y = 0349dc80 7f4fbf37 4f4aeade 3bca9531 4dd58cec 9f307a54 ffc61efc 006d8a2c 9d4979c0 ac44aea7 4fbebbb9 f772aedc b620b01a 7ba7af1b 320430c8 591984f6 01cd4c14 3ef1c7a3

**Comment by liorko87** [comment]
The error come from this line at the examples:
`DlogGroup* dlog = new OpenSSLDlogECF2m("include/configFiles/NISTEC.txt", "K-233");`
Change the path in the example to the correct path of this file.

**Comment by lingering** [comment]
exactly, chage to the corret path can solve this error
