### ISSUE TITLE
libraries in lib does match makefile_lib command

### ISSUE THREAD

**Issue by lingering** [cryptobiu/libscapi#73]
Finally I successfully installed libscapi on ubuntu 16.04 machine. The most critical issus I found is that in master release, the requierd source code used by makefile_libs does NOT match librares in lib directory. As far as I can see, foorqlib json boost miracl OTExtension are not include in lib. So it will occurs many make error. hope you guys can fix this.

**Comment by liorko87** [comment]
Thank you for your comment. I updated the file on the `dev` branch.

**Comment by lingering** [comment]
liorko98 has updated makefile_lib on the dev branch. now We could easily build libs
