### ISSUE TITLE
How to generate circuit using C++?

### ISSUE THREAD

**Issue by Zeinab-Rahmani** [cryptobiu/libscapi#77]
Hello, 
Does libscapi supports generating circuits for c++ using a software or something similar? We are developing a framework that uses large circuits consist of many gates and they can not be written manually (like creating a file and defining the circuit).
Many thanx.

**Comment by liorko87** [comment]
Hello,

If I understand you correctly, your requirement is that libscapi will read the circuit at runtime during th protocol execution from another stream/pipeline?
If so, the answer is no - libscapi currently supports reading circuits from files.

**Comment by Zeinab-Rahmani** [comment]
Hello, in fact, what I mean is to generate a circuit from an analytical function (for example a function that adds to number). 
Thank you.

**Comment by liorko87** [comment]
Hello,

No, libscapi supports only reading circuits from file.

Lior

**Comment by Zeinab-Rahmani** [comment]
Thank you.
