### ISSUE TITLE
Android compile

### ISSUE THREAD

**Issue by patricia93sousa** [cryptobiu/libscapi#8]
Hi,

Anyone is working in integrate this in Android? 

Thanks.

**Comment by liorbiu** [comment]
Hi,

Right now we are not working on integrate libscapi into Android.
Java version of libscapi exist at this GitHub [repository](https://github.com/cryptobiu/scapi).

**Comment by patricia93sousa** [comment]
Are you working in Java for Android, that's it?

**Comment by moriyaw** [comment]
In general, java code should compile in Android.
